version: '3'
services:
  nginx: 
      image: nginx:alpine
      container_name: rel_nginx
      volumes:
      - './nginx/ssl_certs:/etc/ssl_certs'
      - './nginx/conf.d/upstream.conf:/etc/nginx/conf.d/upstream.conf'
      - './nginx/strapi.conf:/etc/nginx/sites-available/strapi.conf'
      - './nginx/strapi.conf:/etc/nginx/sites-enabled/strapi.conf'
      - './nginx/strapi.conf:/etc/nginx/conf.d/default.conf'
      restart: always
      ports:
        - 80:80
        - 443:443
      depends_on:
        - strapi

  strapi:
    image: mm-strapi:latest
    restart: always
    build:
      context: ./backend/strapi
      dockerfile: Dockerfile
    volumes:
      - ./backend/strapi/api:/strapi/api
      - ./backend/strapi/components:/strapi/components
      - ./backend/strapi/extensions:/strapi/extensions
      - ./backend/strapi/config:/strapi/config
    env_file:
      - .env.rel
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    env_file:
      - .env.rel
      