version: '3'
services:
  nginx: 
    image: nginx:alpine
    container_name: dev_nginx
    ports:
      - 80:80
      - 443:443

  strapi:
    image: mm-strapi:latest
    restart: always
    build:
      context: ./backend/strapi
      dockerfile: Dockerfile.dev
    ports:
      - '1337:1337'
    volumes:
      - ./backend/strapi/api:/strapi/api
      - ./backend/strapi/components:/strapi/components
      - ./backend/strapi/extensions:/strapi/extensions
      - ./backend/strapi/config:/strapi/config
    env_file:
      - .env.dev
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    env_file:
      - .env.dev