version: '3'
services:
  nginx:
    image: mm-nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - strapi

  strapi:
    image: mm-strapi:release
    restart: always
    build:
      context: ./backend/strapi
      dockerfile: Dockerfile
    env_file:
      - .env.rel
    depends_on:
      - mysql
      - redis
      - meilisearch

  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env.rel

  redis:
    image: redis:6.0-alpine
    platform: linux/x86_64
    volumes:
      - ./redis-data:/data
    env_file:
      - .env.rel

  meilisearch:
    image: getmeili/meilisearch
    command: ./meilisearch
    volumes:
      - ./meilisearch/data.ms:/data.ms
    ports:
      - "7700:7700"
