FROM strapi/base:14-alpine as base
ENV NODE_ENV development
WORKDIR /strapi
COPY . ./
RUN npm install
RUN npm run build

FROM strapi/base:14-alpine
WORKDIR /strapi
COPY --from=base /strapi .
CMD ["npm", "run", "develop"]